version: "3.9"

services:
  backend:
    build: ./backend
    container_name: pipewise-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: pipewise-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev -- -H 0.0.0.0 -p 3000
    environment:
      - NODE_ENV=development
    restart: unless-stopped
