# backend/tools/registry/__init__.py
"""
This package is reserved for autogenerated tools.

Guidelines:
- Each autogenerated tool should expose:
    - class <YourTool>(BaseTool)
    - def get_tool(**options) -> <YourTool>
- Keep dependencies minimal; prefer runtime imports inside run().
- Do not rely on global state.

The discovery layer can import and introspect tools placed here.
"""
